# Generated by Django 5.0.7 on 2024-10-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_addcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddCourse',
        ),
    ]
